services:
  api:
    restart: always
    volumes:
      - ./:/conf
    build:
      dockerfile: postgrest.Dockerfile
      context: .
    depends_on:
      - db
    ports:
      - 3000:3000
    networks:
      - database
      - caddy_api

  create_user:
    restart: always
    build:
      context: .
      dockerfile: create_user.Dockerfile
    ports:
      - "8088:8088"
    volumes:
      - "./static/profile_pics:/profile_pics"
      - "./create_user.go:/go/src/create_user/create_user.go"
    networks:
      - caddy_api
    
  db:
    restart: always
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      # db and api share a common _private_ and _internal_ network.
      # as the api server handles authentication and has the credentials
      # anyway this is acceptable and saves us from handling db passwords.
      POSTGRES_HOST_AUTH_METHOD: "trust" 
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
      - "./postgres_schema.sql:/docker-entrypoint-initdb.d/schema.sql"
    networks:
      - database

  caddy:
    restart: always
    image: caddy:2-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - "./caddy_data:/data"
      - "./Caddyfile:/etc/caddy/Caddyfile"
      - "./static:/static"
    networks:
      - caddy_api
      - default
      - caddy_auth
  auth_server:
    restart: always
    build:
      context: .
      dockerfile: auth_server.Dockerfile
    volumes:
      - ./auth_server:/auth_server
      - ./secrets.json:/secrets.json
    ports:
      - "8080:8080"
    networks:
      - caddy_auth
  cron:
    restart: always
    build:
      context: .
      dockerfile: cron.Dockerfile
    volumes:
      - ./db_backups:/db_backups
      - ./reports:/reports
      - ./cronjobs/hourly:/etc/periodic/hourly
      - ./cronjobs/monthly:/etc/periodic/monthly
    networks:
      - database
networks:
  database:
    internal: true
  caddy_api:
    internal: true
  caddy_auth:
    internal: true

