services:
  api:
    volumes:
      - ./:/conf
    build:
      dockerfile: postgrest.Dockerfile
      context: .
    depends_on:
      - db
    ports:
      - 3000:3000
    networks:
      - database
      - default # TODO: Remove once we add caddy
    
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      # db and api share a common _private_ and _internal_ network.
      # as the api server handles authentication and has the credentials
      # anyway this is acceptable and saves us from handling db passwords.
      POSTGRES_HOST_AUTH_METHOD: "trust" 
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
      - "./postgres_schema.sql:/docker-entrypoint-initdb.d/schema.sql"
    networks:
      - database
networks:
  database:
    internal: true


